import { Priority, Project, Task, TaskStatus } from './types';

export const INITIAL_PROJECTS: Project[] = [
  { id: 'p1', name: 'SK190 Human Biology', color: '#3b82f6', velocity: 1.0 }, 
  { id: 'p2', name: 'Work', color: '#10b981', velocity: 1.0 },       
  { id: 'p3', name: 'Personal', color: '#f59e0b', velocity: 1.0 },   
];

export const INITIAL_TASKS: Task[] = [
  // --- Week 1: Introduction & Basics ---
  {
    id: 'T1_W1.1a',
    title: 'Course Overview & Study Approach',
    description: 'Review Topic 1 Overview, Learning Outcomes (1.1-1.8), and Section 1.1 "How to study this module." Includes Activity: Exploring LOs.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.1b',
    title: 'Activity 1.1 Icebreaker & 1.2 IHB',
    description: 'Familiarize with forums and the Interactive Human Body (IHB). Mandatory activities.',
    durationMinutes: 45,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.1c',
    title: 'Homeostasis Fundamentals (1.2.1-1.2.4)',
    description: 'Read and define set-point, normal range, regulated/non-regulated variables, and overview of homeostatic mechanisms.',
    durationMinutes: 75,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.2a',
    title: 'Feedback Loops (1.2.5-1.2.7)',
    description: 'Analyze ageing effects, negative feedback (e.g., temperature/glucose), and positive feedback (childbirth). Includes reading data (Figure 1.11).',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.2b',
    title: 'Activity 1.3 Flow charts and feedback loops',
    description: 'Complete flow chart activity using positive feedback loop example. Mandatory activity. TMA01 component.',
    durationMinutes: 60,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.2c',
    title: 'Cellular Organization (1.3.1 - 1.3.2)',
    description: 'Introduction to eukaryotic/prokaryotic cells and basic cell structures (organelles). Preparation for extended activity.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.3a',
    title: 'Activity 1.4 Interactive Cell Exploration',
    description: 'Explore cell membrane and organelles, taking detailed notes (Part 1/2). Mandatory activity. Assessed (iCMA 41).',
    durationMinutes: 90,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.3b',
    title: 'Cell Life and Death (1.3.3 - 1.3.6)',
    description: 'Organelles/ageing, cell types, measurement (µm), senescence, apoptosis. Review metric prefixes.',
    durationMinutes: 45, // Rounded from 40
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.3c',
    title: 'Activity 1.5 Neurons Activity',
    description: 'Read articles and analyze contradictory scientific information. Mandatory activity.',
    durationMinutes: 15, // Rounded from 20
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.4a',
    title: 'Hierarchy of Organization (1.4 - 1.6)',
    description: 'Read about tissues (4 types), extracellular matrix, organs, and organ systems. Focus on structural hierarchy (Figure 1.31).',
    durationMinutes: 90,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W1.4b',
    title: 'Topic 1 Week 1 Review & Consolidation',
    description: 'Review Topic 1 Week 1 learning outcomes, essential definitions, and ethics concepts (1.6). Flexible consolidation time.',
    durationMinutes: 60,
    priority: Priority.LOW,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },

  // --- Week 2: Water & Chemistry ---
  {
    id: 'T1_W2.1a',
    title: 'Introduction & Water for Life (2.1)',
    description: 'Read Introduction, discuss questions (Activity 2.1). Review water balance (Table 2.1). Mandatory activity.',
    durationMinutes: 45,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.1b',
    title: 'Critical Reading (2.2 & 2.2.1)',
    description: 'Read "Eight glasses of water" article and practice critical evaluation. Mandatory activities.',
    durationMinutes: 45,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.1c',
    title: 'Academic Practice (2.2.2)',
    description: 'Introduction to plagiarism, citation, and referencing. Includes Activity 2.4.',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.1d',
    title: 'Water Chemistry Basics (2.3 - 2.3.4)',
    description: 'Solvent role, atoms, elements, periodic table, and molecular formula conventions.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.2a',
    title: 'Activity 2.5 Making notes about water',
    description: 'Watch video (V2.2) and make notes on water composition/structure. Mandatory activity.',
    durationMinutes: 30,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.2b',
    title: 'Activity 2.6 Modelling a water molecule',
    description: 'Build model and upload to OpenStudio. Mandatory activity. Badge criteria.',
    durationMinutes: 30,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.2c',
    title: 'Polarity and Bonds (2.3.5 - 2.3.7)',
    description: 'Subatomic structure, covalent vs ionic bonding, electronegativity, polarity, hydrogen bonds.',
    durationMinutes: 75,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.2d',
    title: 'Biological Molecules (2.4)',
    description: 'Introduction to Carbohydrates, Lipids, Nucleic Acids, and Proteins. Define monomer/polymer.',
    durationMinutes: 45,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.3a',
    title: 'Activity 2.7 Search for Proteins',
    description: 'Complete guided search activity, find a protein, describe function, and practice citation. Mandatory activity. TMA01 component.',
    durationMinutes: 45,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.3b',
    title: 'Passive Transport (2.5.1 - 2.5.3)',
    description: 'Read about diffusion (simple, facilitated) and osmosis (V2.6, V2.7). Includes Activity 2.8 Investigating diffusion.',
    durationMinutes: 45,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.3c',
    title: 'Active & Bulk Transport (2.5.4 - 2.5.5)',
    description: 'Read about active transport (ATP), endocytosis, and exocytosis.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.4a',
    title: 'Scientific Disciplines (2.6)',
    description: 'Read overview of anatomy, physiology, biochemistry, pathology, etc.',
    durationMinutes: 30,
    priority: Priority.LOW,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.4b',
    title: 'Scientific Method (2.7)',
    description: 'Read about the steps (observation, hypothesis, experiment, analysis).',
    durationMinutes: 45,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.4c',
    title: 'Activity 2.9 Practicing the Scientific Method',
    description: 'Work through the red blood cell experiment scenario (osmosis application). Mandatory activity.',
    durationMinutes: 45,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.4d',
    title: 'Ethics, Hazards, Risks (2.9)',
    description: 'Read about ethics (Henrietta Lacks) and risk assessment/hazards (Marie Curie).',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T1_W2.4e',
    title: 'Topic 1 Review',
    description: 'Review Topic 1 Summary and all Learning Outcomes (1.1-1.8). Consolidation.',
    durationMinutes: 60,
    priority: Priority.LOW,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },

  // --- Week 3: Genetics & Investigation ---
  {
    id: 'T2_W1.1a',
    title: 'Introduction & Nature-Nurture (1.1 - 1.1.2)',
    description: 'Review Topic 2 LOs. Read about biological determinism, human genome (V1.1), ethical concerns, and environmental factors.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.1b',
    title: 'Huntington\'s Disease (1.2.1 - 1.2.3)',
    description: 'Read about dominant inheritance (HD), prevalence, genotype/phenotype, and probability. Includes reading pedigree chart and personal testimonies.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.1c',
    title: 'Activity 1.1 Using Punnett squares',
    description: 'Practice calculating probability for dominant inheritance (Hh x Hh, hh x HH). Mandatory activity.',
    durationMinutes: 30,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.1d',
    title: 'Cystic Fibrosis Introduction (1.2.4)',
    description: 'Read about recessive disorders (CF) and CFTR protein role.',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.2a',
    title: 'Cystic Fibrosis Inheritance (1.2.5)',
    description: 'Analyze CF pedigree and Punnett square for carrier parents (CF cf x CF cf).',
    durationMinutes: 45,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.2b',
    title: 'Twin Studies and PKU (1.3.1 - 1.3.2)',
    description: 'Twin studies, PKU (V1.9), and environment overriding genotype (PKU diet).',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.2c',
    title: 'Global Health & Genetics (1.3.3 - 1.3.6)',
    description: 'Famine, obesity, thrifty hypotheses (introduction), global causes of death, sickle cell/malaria interaction.',
    durationMinutes: 75,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.3a',
    title: 'Eye Colour Genetics (1.4)',
    description: 'Read background on OCA2 gene, melanin, and distribution. Preparation for main activity.',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.3b',
    title: 'Activity 1.2 Eye colour distribution (Part 1)',
    description: 'Design methodology (RQ, Hypothesis, Null Hypothesis, Sampling Plan, Ethics) and begin data collection. Mandatory activity. TMA01 component.',
    durationMinutes: 90,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.3c',
    title: 'Activity 1.2 Eye Colour Activity (Part 2)',
    description: 'Continue/complete data collection.',
    durationMinutes: 60,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.4a',
    title: 'Activity 1.2 Eye Colour Activity (Part 3)',
    description: 'Construct the bar chart, upload to OpenStudio, and write the discussion/reflection. Mandatory activity completion.',
    durationMinutes: 90,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W1.4b',
    title: 'Topic 2 Week 1 Review & Consolidation',
    description: 'Review Topic 2 Week 1 learning outcomes (2.1-2.3) and integrate concepts. Prepare for molecular focus in Week 4.',
    durationMinutes: 90,
    priority: Priority.LOW,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },

  // --- Week 4: DNA & Protein Synthesis ---
  {
    id: 'T2_W2.1a',
    title: 'Cell Structure Review (2.1)',
    description: 'Review organelles using interactive cell (Activity 2.1). Mandatory activity.',
    durationMinutes: 30,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.1b',
    title: 'Chromosome Structure and Karyotype (2.1.1 - 2.1.3)',
    description: 'Packaging (V2.1), karyotype, autosomes, sex chromosomes (X, Y), chromosomal disorders.',
    durationMinutes: 90,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.1c',
    title: 'DNA Discovery & Composition (2.2.1 - 2.2.2)',
    description: 'Discovery (V2.3), chemical structure (nucleotides, deoxyribose, 4 bases).',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.2a',
    title: 'DNA Code and Base Pairing (2.2.3)',
    description: 'Code power, complementary base pairing (A-T, C-G), hydrogen bonds.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.2b',
    title: 'DNA Directionality (2.2.4)',
    description: '5\' and 3\' ends, antiparallel strands.',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.2c',
    title: 'The Cell Cycle & Replication (2.3.1 - 2.3.2)',
    description: 'G phases, S phase, telomeres and ageing.',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.2d',
    title: 'DNA Replication Mechanics (2.3.3 - 2.3.4)',
    description: 'Enzymes (helicase, topoisomerase, polymerase, ligase) and semi-conservative replication (V2.6).',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.3a',
    title: 'Mitosis and Cytokinesis (2.3.5)',
    description: 'Review stages of cell division.',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.3b',
    title: 'Activity 2.2 Investigating Mitosis',
    description: 'Work through interactive activity on mitosis stages. Mandatory activity.',
    durationMinutes: 30,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.3c',
    title: 'Proteins (2.4 - 2.5)',
    description: 'Coding/non-coding DNA, amino acid structure, polypeptide formation (V2.8), and protein structure levels.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.3d',
    title: 'Transcription (2.6.1)',
    description: 'Central Dogma, RNA structure, RNA polymerase, template/coding strands (V2.9).',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.4a',
    title: 'Translation (2.6.2 - 2.6.4)',
    description: 'Codons, mRNA, tRNA, codon redundancy (V2.10).',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.4b',
    title: 'Activity 2.3 Central Dogma Application',
    description: 'Use IHB to link CFTR production to the central dogma. Mandatory activity.',
    durationMinutes: 15, // Rounded from 20
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.4c',
    title: 'Stem Cells and Differentiation (2.7 - 2.7.1)',
    description: 'Stem cell potency, self-renewal, differentiation, skin maintenance (keratinocytes, melanocytes).',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W2.4d',
    title: 'DNA Damage and Cancer (2.7.2 - 2.7.4)',
    description: 'Proto-oncogenes, tumor suppressors, UV damage (V2.11), and types of skin cancer.',
    durationMinutes: 45, // Rounded from 40
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },

  // --- Week 5: Meiosis & Socioeconomics ---
  {
    id: 'T2_W3.1a',
    title: 'Meiosis Process (3.1.1)',
    description: 'Review process and significance (haploid gametes, genetic variation).',
    durationMinutes: 45,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.1b',
    title: 'Activity 3.1 Meiosis Interactive',
    description: 'Work through the interactive activity on meiosis stages. Mandatory activity.',
    durationMinutes: 45,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.1c',
    title: 'Activity 3.2 Count the chromosomes',
    description: 'Practice applying chromosome numbers during meiosis. Mandatory activity.',
    durationMinutes: 30,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.1d',
    title: 'From Gametes to Fetus (3.1.2 - 3.1.3)',
    description: 'Zygote, embryo, fetus, cell potency, stages of fetal growth.',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.2a',
    title: 'Activity 3.3 Fetal weight data',
    description: 'Interpreting fetal weight graphs (percentiles). Mandatory activity.',
    durationMinutes: 45,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.2b',
    title: 'Fetal Growth Factors (3.1.4 - 3.1.6)',
    description: 'Fetal growth restriction, impact of race/ethnicity, and socioeconomic status.',
    durationMinutes: 45,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.2c',
    title: 'Activity 3.4 Research Question and Null Hypothesis',
    description: 'Practice composing RQ and null hypothesis. Mandatory activity.',
    durationMinutes: 30,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.2d',
    title: 'Activity 3.5 Graphing Data',
    description: 'Construct a bar graph using SGA/income quintile data and interpret correlation. Mandatory activity.',
    durationMinutes: 60,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.3a',
    title: 'DOHaD and Health Outcomes (3.2 - 3.2.3)',
    description: 'Cardiovascular disease, thrifty genotype, and thrifty phenotype hypotheses.',
    durationMinutes: 90,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.3b',
    title: 'Growth Patterns and Measurement (3.2.4 - 3.2.7)',
    description: 'Catch-up growth, brain-sparing, measurement (ultrasound, ratios), Gambia study (Figure 3.13).',
    durationMinutes: 60,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.3c',
    title: 'Epigenetic Programming (3.2.8)',
    description: 'Epigenetic marks, DNA methylation, histone modification, IGF2 and malnutrition.',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.4a',
    title: 'Bioinformatics (3.3)',
    description: 'Read about big data, databases, and bioinformatics.',
    durationMinutes: 30,
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.4b',
    title: 'Activity 3.6 Searching Open Targets Genetics',
    description: 'Use the tool to find disease links with IGF2. Mandatory activity. Scientific Skills Badge.',
    durationMinutes: 30,
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
  {
    id: 'T2_W3.4c',
    title: 'Topic 2 Review',
    description: 'Review Topic 2 Summary and all Learning Outcomes (2.1-2.10). Integration and final consolidation.',
    durationMinutes: 90,
    priority: Priority.LOW,
    status: TaskStatus.TODO,
    projectId: 'p1',
  },
];